### ISSUE TITLE
PIP | Conda | Etc. Installation

### ISSUE THREAD

**Issue by sirinath** [Emsu/prophet#9]
Above is a great convince to have.

**Comment by Emsu** [comment]
@sirinath I've added installation instructions to the README. I took a look at conda and since prophet is pure python, I think I'll leave it as a pip package. People can still use conda to manage packages with C extensions but use pip to install prophet.

Doing conda packaging properly using cross platform packaging introduces overhead I don't want to manage currently as I would need release build machines for every supported OS. Because it's pure python, I could release an OSX version and people can download and manually convert the package for their OS and it should work, but the package not found errors for specific OS's will confuse people new to conda.
